### ISSUE TITLE
Create separate artifact for testing

### ISSUE THREAD

**Issue by jart** [google/safe-html-types#2]
@mikesamuel while generating a [Bazel config](https://gist.github.com/jart/c325bba360c889261415872cc0b6700f) for Soy, I noticed that this project schlepped Guava testlib and junit into the transitive closure. I'm sending you a CL to mark the guava-testlib dependency as optional. I recommend creating a separate pom artifact for your html testing directory.

**Comment by mikesamuel** [comment]
Addressed in https://github.com/google/safe-html-types/commit/c1772e06e729ea177bb749ff02dcb4e67e27d59d
